[package]
name = "unicode-consts"
version = "0.2.3"
edition = "2024"
description = "named constants for all unicode characters"
repository = "https://github.com/sermuns/unicode-consts"
license = "Apache-2.0 OR MIT"
categories = ["no-std", "no-std::no-alloc"]

[features]
adlam = []
aegean_numbers = []
ahom = []
alchemical_symbols = []
alphabetic_presentation_forms = []
anatolian_hieroglyphs = []
ancient_greek_musical_notation = []
ancient_greek_numbers = []
ancient_symbols = []
arabic = []
arabic_extended_a = []
arabic_extended_b = []
arabic_extended_c = []
arabic_mathematical_alphabetic_symbols = []
arabic_presentation_forms_a = []
arabic_presentation_forms_b = []
arabic_supplement = []
armenian = []
arrows = []
avestan = []
balinese = []
bamum = []
bamum_supplement = []
basic_latin = []
bassa_vah = []
batak = []
bengali = []
beria_erfe = []
bhaiksuki = []
block_elements = []
bopomofo = []
bopomofo_extended = []
box_drawing = []
brahmi = []
braille_patterns = []
buginese = []
buhid = []
byzantine_musical_symbols = []
carian = []
caucasian_albanian = []
chakma = []
cham = []
cherokee = []
cherokee_supplement = []
chess_symbols = []
chorasmian = []
cjk_compatibility = []
cjk_compatibility_forms = []
cjk_compatibility_ideographs = []
cjk_compatibility_ideographs_supplement = []
cjk_radicals_supplement = []
cjk_strokes = []
cjk_symbols_and_punctuation = []
cjk_unified_ideographs = []
cjk_unified_ideographs_extension_a = []
cjk_unified_ideographs_extension_b = []
cjk_unified_ideographs_extension_c = []
cjk_unified_ideographs_extension_d = []
cjk_unified_ideographs_extension_e = []
cjk_unified_ideographs_extension_f = []
cjk_unified_ideographs_extension_g = []
cjk_unified_ideographs_extension_h = []
cjk_unified_ideographs_extension_i = []
cjk_unified_ideographs_extension_j = []
combining_diacritical_marks = []
combining_diacritical_marks_extended = []
combining_diacritical_marks_for_symbols = []
combining_diacritical_marks_supplement = []
combining_half_marks = []
common_indic_number_forms = []
control_pictures = []
coptic = []
coptic_epact_numbers = []
counting_rod_numerals = []
cuneiform = []
cuneiform_numbers_and_punctuation = []
currency_symbols = []
cypriot_syllabary = []
cypro_minoan = []
cyrillic = []
cyrillic_extended_a = []
cyrillic_extended_b = []
cyrillic_extended_c = []
cyrillic_extended_d = []
cyrillic_supplement = []
deseret = []
devanagari = []
devanagari_extended = []
devanagari_extended_a = []
dingbats = []
dives_akuru = []
dogra = []
domino_tiles = []
duployan = []
early_dynastic_cuneiform = []
egyptian_hieroglyph_format_controls = []
egyptian_hieroglyphs = []
egyptian_hieroglyphs_extended_a = []
elbasan = []
elymaic = []
emoticons = []
enclosed_alphanumeric_supplement = []
enclosed_alphanumerics = []
enclosed_cjk_letters_and_months = []
enclosed_ideographic_supplement = []
ethiopic = []
ethiopic_extended = []
ethiopic_extended_a = []
ethiopic_extended_b = []
ethiopic_supplement = []
garay = []
general_punctuation = []
geometric_shapes = []
geometric_shapes_extended = []
georgian = []
georgian_extended = []
georgian_supplement = []
glagolitic = []
glagolitic_supplement = []
gothic = []
grantha = []
greek_and_coptic = []
greek_extended = []
gujarati = []
gunjala_gondi = []
gurmukhi = []
gurung_khema = []
halfwidth_and_fullwidth_forms = []
hangul_compatibility_jamo = []
hangul_jamo = []
hangul_jamo_extended_a = []
hangul_jamo_extended_b = []
hangul_syllables = []
hanifi_rohingya = []
hanunoo = []
hatran = []
hebrew = []
high_private_use_surrogates = []
high_surrogates = []
hiragana = []
ideographic_description_characters = []
ideographic_symbols_and_punctuation = []
imperial_aramaic = []
indic_siyaq_numbers = []
inscriptional_pahlavi = []
inscriptional_parthian = []
ipa_extensions = []
javanese = []
kaithi = []
kaktovik_numerals = []
kana_extended_a = []
kana_extended_b = []
kana_supplement = []
kanbun = []
kangxi_radicals = []
kannada = []
katakana = []
katakana_phonetic_extensions = []
kawi = []
kayah_li = []
kharoshthi = []
khitan_small_script = []
khmer = []
khmer_symbols = []
khojki = []
khudawadi = []
kirat_rai = []
lao = []
latin_1_supplement = []
latin_extended_a = []
latin_extended_additional = []
latin_extended_b = []
latin_extended_c = []
latin_extended_d = []
latin_extended_e = []
latin_extended_f = []
latin_extended_g = []
lepcha = []
letterlike_symbols = []
limbu = []
linear_a = []
linear_b_ideograms = []
linear_b_syllabary = []
lisu = []
lisu_supplement = []
low_surrogates = []
lycian = []
lydian = []
mahajani = []
mahjong_tiles = []
makasar = []
malayalam = []
mandaic = []
manichaean = []
marchen = []
masaram_gondi = []
mathematical_alphanumeric_symbols = []
mathematical_operators = []
mayan_numerals = []
medefaidrin = []
meetei_mayek = []
meetei_mayek_extensions = []
mende_kikakui = []
meroitic_cursive = []
meroitic_hieroglyphs = []
miao = []
miscellaneous_mathematical_symbols_a = []
miscellaneous_mathematical_symbols_b = []
miscellaneous_symbols = []
miscellaneous_symbols_and_arrows = []
miscellaneous_symbols_and_pictographs = []
miscellaneous_symbols_supplement = []
miscellaneous_technical = []
modi = []
modifier_tone_letters = []
mongolian = []
mongolian_supplement = []
mro = []
multani = []
musical_symbols = []
myanmar = []
myanmar_extended_a = []
myanmar_extended_b = []
myanmar_extended_c = []
nabataean = []
nag_mundari = []
nandinagari = []
new_tai_lue = []
newa = []
nko = []
number_forms = []
nushu = []
nyiakeng_puachue_hmong = []
ogham = []
ol_chiki = []
ol_onal = []
old_hungarian = []
old_italic = []
old_north_arabian = []
old_permic = []
old_persian = []
old_sogdian = []
old_south_arabian = []
old_turkic = []
old_uyghur = []
optical_character_recognition = []
oriya = []
ornamental_dingbats = []
osage = []
osmanya = []
ottoman_siyaq_numbers = []
pahawh_hmong = []
palmyrene = []
pau_cin_hau = []
phags_pa = []
phaistos_disc = []
phoenician = []
phonetic_extensions = []
phonetic_extensions_supplement = []
playing_cards = []
private_use_area = []
psalter_pahlavi = []
rejang = []
rumi_numeral_symbols = []
runic = []
samaritan = []
saurashtra = []
sharada = []
sharada_supplement = []
shavian = []
shorthand_format_controls = []
siddham = []
sidetic = []
sinhala = []
sinhala_archaic_numbers = []
small_form_variants = []
small_kana_extension = []
sogdian = []
sora_sompeng = []
soyombo = []
spacing_modifier_letters = []
specials = []
sundanese = []
sundanese_supplement = []
sunuwar = []
superscripts_and_subscripts = []
supplemental_arrows_a = []
supplemental_arrows_b = []
supplemental_arrows_c = []
supplemental_mathematical_operators = []
supplemental_punctuation = []
supplemental_symbols_and_pictographs = []
supplementary_private_use_area_a = []
supplementary_private_use_area_b = []
sutton_signwriting = []
syloti_nagri = []
symbols_and_pictographs_extended_a = []
symbols_for_legacy_computing = []
symbols_for_legacy_computing_supplement = []
syriac = []
syriac_supplement = []
tagalog = []
tagbanwa = []
tags = []
tai_le = []
tai_tham = []
tai_viet = []
tai_xuan_jing_symbols = []
tai_yo = []
takri = []
tamil = []
tamil_supplement = []
tangsa = []
tangut = []
tangut_components = []
tangut_components_supplement = []
tangut_supplement = []
telugu = []
thaana = []
thai = []
tibetan = []
tifinagh = []
tirhuta = []
todhri = []
tolong_siki = []
toto = []
transport_and_map_symbols = []
tulu_tigalari = []
ugaritic = []
unified_canadian_aboriginal_syllabics = []
unified_canadian_aboriginal_syllabics_extended = []
unified_canadian_aboriginal_syllabics_extended_a = []
vai = []
variation_selectors = []
variation_selectors_supplement = []
vedic_extensions = []
vertical_forms = []
vithkuqi = []
wancho = []
warang_citi = []
yezidi = []
yi_radicals = []
yi_syllables = []
yijing_hexagram_symbols = []
zanabazar_square = []
znamenny_musical_notation = []
